package com.hejinwei.majiang.dal.mybatis.mapper;

import com.hejinwei.majiang.dal.mybatis.model.FacePhoto;
import com.hejinwei.majiang.dal.mybatis.model.FacePhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacePhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int countByExample(FacePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int deleteByExample(FacePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int insert(FacePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int insertSelective(FacePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    List<FacePhoto> selectByExample(FacePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    FacePhoto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") FacePhoto record, @Param("example") FacePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int updateByExample(@Param("record") FacePhoto record, @Param("example") FacePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int updateByPrimaryKeySelective(FacePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_photo
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    int updateByPrimaryKey(FacePhoto record);
}