package com.hejinwei.majiang.dal.mybatis.model;

public class FacePhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.xm
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.sfz
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String sfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.xp
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String xp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.all_time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String allTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.user_id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.state
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.user_name
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_photo.score
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.id
     *
     * @return the value of face_photo.id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.id
     *
     * @param id the value for face_photo.id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.xm
     *
     * @return the value of face_photo.xm
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.xm
     *
     * @param xm the value for face_photo.xm
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.sfz
     *
     * @return the value of face_photo.sfz
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getSfz() {
        return sfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.sfz
     *
     * @param sfz the value for face_photo.sfz
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setSfz(String sfz) {
        this.sfz = sfz == null ? null : sfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.xp
     *
     * @return the value of face_photo.xp
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getXp() {
        return xp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.xp
     *
     * @param xp the value for face_photo.xp
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setXp(String xp) {
        this.xp = xp == null ? null : xp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.time
     *
     * @return the value of face_photo.time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.time
     *
     * @param time the value for face_photo.time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.all_time
     *
     * @return the value of face_photo.all_time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getAllTime() {
        return allTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.all_time
     *
     * @param allTime the value for face_photo.all_time
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setAllTime(String allTime) {
        this.allTime = allTime == null ? null : allTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.user_id
     *
     * @return the value of face_photo.user_id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.user_id
     *
     * @param userId the value for face_photo.user_id
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.state
     *
     * @return the value of face_photo.state
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.state
     *
     * @param state the value for face_photo.state
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.user_name
     *
     * @return the value of face_photo.user_name
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.user_name
     *
     * @param userName the value for face_photo.user_name
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_photo.score
     *
     * @return the value of face_photo.score
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_photo.score
     *
     * @param score the value for face_photo.score
     *
     * @mbggenerated Fri Dec 04 16:38:56 CST 2015
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }
}