package com.hejinwei.majiang.dal.mybatis.model;

import java.util.Date;

public class SmsTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.template_id
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.description
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.content
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.raw_add_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    private Date rawAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.raw_update_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    private Date rawUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.template_id
     *
     * @return the value of sms_template.template_id
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.template_id
     *
     * @param templateId the value for sms_template.template_id
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.description
     *
     * @return the value of sms_template.description
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.description
     *
     * @param description the value for sms_template.description
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.content
     *
     * @return the value of sms_template.content
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.content
     *
     * @param content the value for sms_template.content
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.raw_add_time
     *
     * @return the value of sms_template.raw_add_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.raw_add_time
     *
     * @param rawAddTime the value for sms_template.raw_add_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.raw_update_time
     *
     * @return the value of sms_template.raw_update_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.raw_update_time
     *
     * @param rawUpdateTime the value for sms_template.raw_update_time
     *
     * @mbggenerated Fri Nov 13 11:44:16 CST 2015
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }
}